# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-12-17 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181217_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerCourse',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_org',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_banner',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_tell',
        ),
        migrations.RemoveField(
            model_name='course',
            name='youneed_know',
        ),
    ]
